language: node_js
node_js:
- '6.9'
- '7.0'
- '7.2'
script:
- npm test
- npm install istanbul codacy-coverage mocha-lcov-reporter -g
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage && rm -rf ./coverage
cache:
  directories:
  - node_modules
